version: "3.4"
services:
 server:
  container_name: server_example
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "3000:3000"
  expose:
    - "3000"
  volumes:
    - ./src:/usr/src/app/src
    - ./nodemon.json:/usr/src/app/nodemon.json
  command: npm run dev
